PATH: experiments
LOG: True
PRINT: False
NONCHECKKEYS:
- NONCHECKKEYS
- LOG
- PRINT
- PATH
- ADD
- GROUP
- GROUPPATHLIST
- GROUPNAMELIST
- BRANCH
- GLOBAL
- WORKNAME
- WORKPATH
- DEEP
- MAINPATH
- VERSION
- BRANCHCONTINUE
- PARENTPATH
- INHERITCHANGE
- INHERITREPLACE