GROUP: True

INHERIT: ~
#  test: test  <==>  SELF.test: SELF.test
#  WORKDATA.model: WORKDATA.model
BRANCH:
  # # list | range
  # type: list
  # # key: SELF.seed
  # key: seed
  # value: [1, 2, 3, 4, 5]
  type: list
  key: train.loss_compute.optimizer.args.learning_rate
  value: [0.00005, 0.0001, 0.0002, 0.0003, 0.0004, 0.0005]

group:
  group_strategies: strategies.group_strategies.pass_and_work
  
WORKFLOW:
  pass_and_work:
    FUNCTION: SELF.group.group_strategies
    INPUT:
      configs: SELF
      workdata: WORKDATA
      path_dir: SELF.MAINPATH
      group_cfg: SELF.group
    OUTPUT: 
    - DETAIL